# Generated by Django 4.2.3 on 2023-12-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('RUB', 'Рубли'), ('EUR', 'Евро')], max_length=3),
        ),
    ]
