# Generated by Django 4.2.3 on 2023-12-28 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_order_total_price_alter_item_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'Скидка на заказ', 'verbose_name_plural': 'Скидки на заказ'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ на покупку', 'verbose_name_plural': 'Заказы на покупку'},
        ),
        migrations.AlterModelOptions(
            name='tax',
            options={'verbose_name': 'Налог на заказ', 'verbose_name_plural': 'Налоги на заказ'},
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Скидка(%)'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('RUB', 'Рубли'), ('EUR', 'Евро')], max_length=3, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='payments.item', verbose_name='Товары в заказе'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Скидка(%)'),
        ),
    ]
