# Generated by Django 4.2.3 on 2023-12-28 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_discount_discount_amount_alter_order_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tax',
            name='order',
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.DeleteModel(
            name='Tax',
        ),
    ]
