version: '3'

services:
  db:
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: simple
      POSTGRES_PASSWORD: 3gGG*2n4
      POSTGRES_DB: simple_db

  web:
    build: .
    command: gunicorn simplesolution.wsgi:application --bind 0.0.0.0:8888
    volumes:
      - ./simplesolution_project:/app
    ports:
      - "8888:8888"
    depends_on:
      - db
    environment:
      - DJANGO_SECRET_KEY=django-insecure-*99(uiv=_$sye=&xrdst^rny&$p8vcsg%@hb)dsl5qw^g-j4pn

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./simplesolution_project/static:/static
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - web

volumes:
  pgdata:
