# Generated by Django 4.2.3 on 2023-12-28 18:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_discount_options_alter_item_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(100.0)], verbose_name='Скидка(%)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='orders', to='payments.item', verbose_name='Товары в заказе'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(100.0)], verbose_name='Налог(%)'),
        ),
    ]
