    # Generated by Django 4.1.6 on 2023-12-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_remove_tax_order_delete_discount_delete_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('RUB', 'Рубль'), ('USD', 'Доллар')], max_length=3, verbose_name='Валюта'),
        ),
    ]
